{% set name = "pycsep" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycsep-{{ version }}.tar.gz
  sha256: f30bba679f2f3d141da87fd45870a4aaa22a4dbab33daa366caad694160d24af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cartopy
    - matplotlib-base
    - numpy 
    - obspy
    - pandas
    - pyproj
    - python >=3.7
    - python-dateutil
    - scipy
    - shapely
    - mercantile

test:
  imports:
    - csep
    - csep.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SCECCode/pycsep
  summary: Python tools from the Collaboratory for the Study of Earthquake Predictability
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wsavran
