{% set name = "pycsep" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycsep-{{ version }}.tar.gz
  sha256: 0ad683e02c6eec125360442c06bf80970b359e1a3a8204421ed222b194f340c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cartopy
    - matplotlib-base
    - numpy
    - obspy
    - pandas
    - pyproj
    - python >=3.7
    - python-dateutil
    - scipy

test:
  imports:
    - csep
    - csep.core
    - csep.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SCECCode/csep2
  summary: Python tools from the Collaboratory for the Study of Earthquake Predictability
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wsavran
