{% set name = "pycsep" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycsep-{{ version }}.tar.gz
  sha256: 130897fcc6a2e9d1a58ccc26feff3c3ab7c3e2085a28d7b30eb087950c89928f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cartopy
    - matplotlib-base
    - numpy
    - obspy
    - pandas
    - pyproj
    - python >=3.7
    - python-dateutil
    - scipy

test:
  imports:
    - csep
    - csep.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SCECCode/pycsep
  summary: Python tools from the Collaboratory for the Study of Earthquake Predictability
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wsavran
