{% set name = "pycsep" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycsep-{{ version }}.tar.gz
  sha256: 3d1d278780a4a89db93b8b5b24b3b2bc465729c0e4c4457abda1e244e0f2a501

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cartopy
    - matplotlib-base
    - numpy
    - obspy
    - pandas
    - pyproj
    - python >=3.7
    - python-dateutil
    - scipy

test:
  imports:
    - csep
    - csep.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SCECCode/pycsep
  summary: Python tools from the Collaboratory for the Study of Earthquake Predictability
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wsavran
