{% set name = "pycsep" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycsep-{{ version }}.tar.gz
  sha256: baec84198eaa6981a4cb4c321260085f81223c68cf0e578df1b772a18900fd12

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cartopy
    - matplotlib-base
    - numpy <=1.21.5
    - obspy
    - pandas
    - pyproj
    - python >=3.7
    - python-dateutil
    - scipy
    - mercantile

test:
  imports:
    - csep
    - csep.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SCECCode/pycsep
  summary: Python tools from the Collaboratory for the Study of Earthquake Predictability
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wsavran
